### ISSUE TITLE
Release v0.5.1?

### ISSUE THREAD

**Issue by dkarrasch** [JuliaMolSim/NeighbourLists.jl#22]
In a recent nanosoldier run, there occurred warnings for this package that seem to be fixed meanwhile, but not yet released.

**Comment by cortner** [comment]
weve been releasing the package through the MolSim Registry but if there is interest we can register it again with General

**Comment by cortner** [comment]
or are you saying that we fixed problems that haven't been released at all??

**Comment by cortner** [comment]
and sorry for the slow reply - I had a busy week.

**Comment by cortner** [comment]
note I've submitted a PR to General, so I think this is ready to close.
